name: Build & publish images
on: 
  workflow_dispatch:
    inputs:
      version:
        type: text
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  get_methods:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: | 
          cd methods
          ls | jq -R -s -c 'split("\n")[:-1]'
          echo "::set-output name=matrix::$(ls | jq -R -s -c 'split("\n")[:-1]')"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build-and-push-image:
    needs: get_methods
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        folder: ${{ fromJson(needs.get_methods.outputs.matrix) }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/ldimbenchmark/${{ matrix.folder }}

      - name: Get Version
        id: version
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
        working-directory: methods/${{ matrix.folder }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: methods/${{ matrix.folder }}/
          file: methods/${{ matrix.folder }}/Dockerfile
          push: true
          #tags: ghcr.io/ldimbenchmark/ldimbenchmark:${{ env.VERSION }}
          tags: ghcr.io/ldimbenchmark/${{ matrix.folder }}:${{ env.VERSION }} , ghcr.io/ldimbenchmark/${{ matrix.folder }}:latest
          labels: | 
            ${{ steps.meta.outputs.labels }}
            LDIMBENCHMARK_VERSION=${{ github.event.inputs.version }}
          build-args: |
            LDIMBENCHMARK_VERSION=${{ github.event.inputs.version }}


      # - name: Build and export to Docker
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     load: true
      #     tags: ${{ env.TEST_TAG }}
      # - name: Test
      #   run: |
      #     docker run --rm ${{ env.TEST_TAG }}
      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ${{ env.LATEST_TAG }}
